# Generated by Django 6.0.6 on 2026-06-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_delivery_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo_url", models.TextField(blank=True)),
                ("vehicle", models.CharField(blank=True, max_length=120)),
                ("plate_number", models.CharField(blank=True, max_length=60)),
                ("zone", models.CharField(blank=True, max_length=150)),
                ("max_active_orders", models.PositiveSmallIntegerField(default=3)),
                ("status", models.CharField(choices=[("available", "Available"), ("busy", "Busy"), ("offline", "Offline")], default="available", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="courier_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
