# Generated by Django 6.0.6 on 2026-06-21 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'representative'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
