# Generated by Django 6.0.6 on 2026-06-21 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_default_addresses(apps, schema_editor):
    Address = apps.get_model("locations", "Address")
    duplicate_users = (
        Address.objects.filter(is_default=True)
        .values_list("user_id", flat=True)
        .order_by()
        .distinct()
    )
    for user_id in duplicate_users.iterator():
        default_ids = list(
            Address.objects.filter(user_id=user_id, is_default=True)
            .order_by("-created_at", "-id")
            .values_list("id", flat=True)
        )
        if len(default_ids) > 1:
            Address.objects.filter(id__in=default_ids[1:]).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-is_default', '-updated_at', '-id')},
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.city'),
        ),
        migrations.RunPython(
            normalize_default_addresses,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='locations_one_default_address_per_user'),
        ),
    ]
